# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - 'terraformFile/*'

variables:
  # There must be an Azure Service Connection with that name defined in your Azure DevOps settings. See https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
  serviceConnection: 'test'
  azureLocation: 'eastus'
  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/terraformFile'
  terraformVersion: '0.12.25'

stages:
  - stage: TerraformContinuousIntegration
    displayName: Terraform Module - CI
    jobs:
    - job: TerraformContinuousIntegrationJob
      displayName: TerraformContinuousIntegration - CI Job
      pool:
        vmImage: ubuntu-20.04
      steps:
      # Step 2: install Terraform on the Azure Pipelines agent
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: $(terraformVersion)
      - task: TerraformCLI@0
        displayName: 'Run terraform destroy'
        inputs:
          command: 'destroy'
          allowTelemetryCollection: true
          workingDirectory: $(terraformWorkingDirectory)
          environmentServiceName: $(serviceConnection)

